-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

Create Table Users(
	UID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(256) UNIQUE NOT NULL,
	pwd VARCHAR(256) NOT NULL,
	address VARCHAR (256)NOT NULL,
	firstname VARCHAR(256) NOT NULL,
	lastname VARCHAR(256) NOT NULL,
	balance INTEGER NOT NULL,
	is_seller VARCHAR(1) NOT NULL
);

CREATE TABLE Category (
    cat_name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Products (
	product_name VARCHAR(255) NOT NULL,
	product_id INT UNIQUE NOT NULL PRIMARY KEY,
	product_description VARCHAR(255) NOT NULL,
	image_id VARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
	link VARCHAR(255) NOT NULL,
	UID REFERENCES Users(UID),
	quantity FLOAT NOT NULL,
    available VARCHAR(1) NOT NULL
);

CREATE TABLE product_review(
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UID INTEGER NOT NULL REFERENCES Users,
    product_id INTEGER NOT NULL REFERENCES Products,
    rev_timestamp TIMESTAMP without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
    rating INTEGER NOT NULL,
    review VARCHAR(100) NOT NULL, UNIQUE(uid, product_id)
);

CREATE TABLE Orders(
   user REFERENCES Users(UID) PRIMARY KEY,
   prod REFERENCES Products(product_id) PRIMARY KEY,
   order _quantity INTEGER NOT NULL,
   Date INTEGER default NULL
);






